[package]
name = "nes-emulator"
version = "0.1.0"
edition = "2021"

[dependencies]
bitflags = "2.9.0"
chrono = "0.4.40"
pixels = "0.15.0"
strum = "0.27.1"
strum_macros = "0.27.1"
winit = "0.29.15"
winit_input_helper = "0.16.0"
